const API_BASE=window.STOCKQUEST_CONFIG?.API_BASE||"/api";
const quoteCache=new Map(),graphCache=new Map(),searchCache=new Map(),inFlight=new Map();const SETTINGS={quoteTTL:30000,graphTTL:300000,searchTTL:300000,staleTTL:1800000,retries:2,retryDelay:700,maxConcurrent:3};const queue=[];let activeRequests=0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),norm=t=>String(t||"").trim().toUpperCase(),fresh=(e,t)=>!!e&&Date.now()-e.time<t,usable=e=>!!e&&e.value!==undefined&&Date.now()-e.time<SETTINGS.staleTTL;
function runQueued(task){return new Promise((resolve,reject)=>{queue.push({task,resolve,reject});pump();});}function pump(){while(activeRequests<SETTINGS.maxConcurrent&&queue.length){const x=queue.shift();activeRequests++;Promise.resolve().then(x.task).then(x.resolve,x.reject).finally(()=>{activeRequests--;pump();});}}function dedupe(k,task){if(inFlight.has(k))return inFlight.get(k);const p=runQueued(task).finally(()=>inFlight.delete(k));inFlight.set(k,p);return p;}
async function fetchJSON(url){let last;for(let i=0;i<=SETTINGS.retries;i++){try{const r=await fetch(url,{cache:"no-store"}),d=await r.json().catch(()=>null);if(!r.ok||d?.error)throw new Error(d?.error||("HTTP "+r.status));return d;}catch(e){last=e;if(i<SETTINGS.retries)await sleep(SETTINGS.retryDelay*Math.pow(2,i));}}throw last||new Error("Request failed.");}
async function getStock(ticker){const s=norm(ticker);if(!s)return{price:null,green:true,stale:false,cached:false,error:"Missing ticker."};const c=quoteCache.get(s);if(fresh(c,SETTINGS.quoteTTL))return{...c.value,cached:true,stale:false};try{const v=await dedupe("quote:"+s,async()=>{const d=await fetchJSON(API_BASE+"/price?symbol="+encodeURIComponent(s));const p=Number(d?.price);if(!Number.isFinite(p)||p<=0)throw new Error("No valid price returned.");const old=quoteCache.get(s)?.value?.price,r={price:p,green:Number.isFinite(old)?p>=old:true,stale:false,error:null};quoteCache.set(s,{time:Date.now(),value:r});return r;});return{...v,cached:false,stale:false};}catch(e){if(usable(quoteCache.get(s)))return{...quoteCache.get(s).value,cached:true,stale:true,error:e?.message||"Refresh failed"};return{price:null,green:true,stale:false,cached:false,error:e?.message||"Unable to load price."};}}
async function getGraphData(ticker){const s=norm(ticker);if(!s)return[];const c=graphCache.get(s);if(fresh(c,SETTINGS.graphTTL))return c.value.slice();try{const v=await dedupe("graph:"+s,async()=>{const d=await fetchJSON(API_BASE+"/chart?symbol="+encodeURIComponent(s));if(!Array.isArray(d?.values)||d.values.length<2)throw new Error("Not enough chart data.");graphCache.set(s,{time:Date.now(),value:d.values});return d.values;});return v.slice();}catch(e){console.error("Graph failed for "+s,e);return usable(graphCache.get(s))?graphCache.get(s).value.slice():[];}}
async function fetchSearch(query){const q=String(query||"").trim();if(!q)return[];const k=q.toLowerCase(),c=searchCache.get(k);if(fresh(c,SETTINGS.searchTTL))return c.value.map(x=>({...x}));try{const v=await dedupe("search:"+k,async()=>{const d=await fetchJSON(API_BASE+"/search?q="+encodeURIComponent(q));const list=Array.isArray(d?.data)?d.data:[];searchCache.set(k,{time:Date.now(),value:list});return list;});return v.map(x=>({...x}));}catch(e){console.error("Search failed:",e);return usable(searchCache.get(k))?searchCache.get(k).value.map(x=>({...x})):[];}}
function clearStockCache(ticker){if(!ticker){quoteCache.clear();graphCache.clear();searchCache.clear();return;}const s=norm(ticker);quoteCache.delete(s);graphCache.delete(s);}function getDataLayerStatus(ticker){const s=norm(ticker);return{activeRequests,queuedRequests:queue.length,quoteCached:quoteCache.has(s),graphCached:graphCache.has(s),quoteInFlight:inFlight.has("quote:"+s),graphInFlight:inFlight.has("graph:"+s),configured:true};}
